### ISSUE TITLE
i add but not saving

### ISSUE THREAD

**Issue by mahalamobile** [Polkadex-Substrate/Documentation#2]
I add settings->developer

{
  "OrderType": {
    "_enum": [
      "BidLimit",
      "BidMarket",
      "AskLimit",
      "AskMarket"
    ]
  },
  "Order": {
    "id": "Hash",
    "trading_pair": "Hash",
    "trader": "AccountId",
    "price": "FixedU128",
    "quantity": "FixedU128",
    "order_type": "OrderType"
  },
  "MarketData": {
    "low": "FixedU128",
    "high": "FixedU128",
    "volume": "FixedU128"
  },
  "LinkedPriceLevel": {
    "next": "Option<FixedU128>",
    "prev": "Option<FixedU128>",
    "orders": "Vec<Order>"
  },
  "Orderbook": {
    "trading_pair": "Hash",
    "base_asset_id": "u32",
    "quote_asset_id": "u32",
    "best_bid_price": "FixedU128",
    "best_ask_price": "FixedU128"
  },
  "LookupSource": "AccountId",
  "Address": "AccountId"
}

and Save

when i return this is gone?

**Comment by Gauthamastro** [comment]
This issue is not related to Polkadex, you can create an issue at https://github.com/polkadot-js/apps

Closing this for now.

**Comment by mahalamobile** [comment]
is there an exposed api?
